PACKAGE_NAME="i2c-piix4-asf"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="i2c-piix4"
DEST_MODULE_LOCATION[0]="/updates"
MAKE[0]="make -C /usr/lib/modules/${kernelver}/build M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
AUTOINSTALL="yes"
